cam_0_enable: true
cam_0_frame_id: "cam_0_link"
cam_0_pose: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
cam_0_image_queue_size: 10
cam_0_image_latch: false
cam_0_info_queue_size: 10
cam_0_info_latch: false

cam_1_enable: true
cam_1_frame_id: "cam_1_link"
cam_1_pose: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
cam_1_image_queue_size: 10
cam_1_image_latch: false
cam_1_info_queue_size: 10
cam_1_info_latch: false

cam_2_enable: true
cam_2_frame_id: "cam_2_link"
cam_2_pose: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
cam_2_image_queue_size: 10
cam_2_image_latch: false
cam_2_info_queue_size: 10
cam_2_info_latch: false

cam_3_enable: true
cam_3_frame_id: "cam_3_link"
cam_3_pose: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
cam_3_image_queue_size: 10
cam_3_image_latch: false
cam_3_info_queue_size: 10
cam_3_info_latch: false
